function utf8_musl_files()
  return {
    'utf8-musl/env/__environ.cc',
    'utf8-musl/env/getenv.cc',
    'utf8-musl/env/putenv.cc',
    'utf8-musl/env/setenv.cc',
    'utf8-musl/env/unsetenv.cc',
    'utf8-musl/internal/floatscan.cc',
    'utf8-musl/internal/intscan.cc',
    'utf8-musl/internal/shgetc.cc',
    'utf8-musl/internal/tz_state.cc',
    'utf8-musl/multibyte/c16rtomb.cc',
    'utf8-musl/multibyte/c32rtomb.cc',
    'utf8-musl/multibyte/internal.cc',
    'utf8-musl/multibyte/mbrtoc16.cc',
    'utf8-musl/multibyte/mbrtoc32.cc',
    'utf8-musl/multibyte/mbrtowc.cc',
    'utf8-musl/multibyte/mbsinit.cc',
    'utf8-musl/multibyte/wcrtomb.cc',
    'utf8-musl/multibyte/wctomb.cc',
    'utf8-musl/stdio/__console_close.cc',
    'utf8-musl/stdio/__console_seek.cc',
    'utf8-musl/stdio/__stdio_read.cc',
    'utf8-musl/stdio/__stdio_write.cc',
    'utf8-musl/stdio/__overflow.cc',
    'utf8-musl/stdio/__toread.cc',
    'utf8-musl/stdio/__towrite.cc',
    'utf8-musl/stdio/__uflow.cc',
    'utf8-musl/stdio/fflush.cc',
    'utf8-musl/stdio/fgetc.cc',
    'utf8-musl/stdio/fgets.cc',
    'utf8-musl/stdio/fputc.cc',
    'utf8-musl/stdio/fread.cc',
    'utf8-musl/stdio/fwrite.cc',
    'utf8-musl/stdio/stderr.cc',
    'utf8-musl/stdio/stdin.cc',
    'utf8-musl/stdio/stdout.cc',
    'utf8-musl/stdio/ungetc.cc',
    'utf8-musl/stdio/vfprintf.cc',
    'utf8-musl/stdio/vfscanf.cc',
    'utf8-musl/stdio/vsnprintf.cc',
    'utf8-musl/stdio/vsscanf.cc',
    'utf8-musl/stdlib/strtox.cc',
    'utf8-musl/string/strchrnul.cc',
    'utf8-musl/time/__month_to_secs.cc',
    'utf8-musl/time/__tm_to_secs.cc',
    'utf8-musl/time/__year_to_secs.cc',
    'utf8-musl/time/strftime.cc',
    'utf8-musl/time/wcsftime.cc',
    'utf8-musl/ucrt/console_channel.cc',
    'utf8-musl/ucrt/is_console.cc',
    'utf8-musl/ucrt/native_bridge.cc',
    'utf8-musl/ucrt/utf8_argv.cc',
    'utf8-musl/ucrt/utf8_buffer.cc',
    'utf8-musl/unistd/read.cc',
    'utf8-musl/unistd/readv.cc',
    'utf8-musl/unistd/write.cc',
    'utf8-musl/unistd/writev.cc',

    'utf8-ucrt/convert/_fptostr.cc',
    'utf8-ucrt/convert/c32rtomb.cc',
    'utf8-ucrt/convert/cfout.cc',
    'utf8-ucrt/convert/common_utf8.cc',
    'utf8-ucrt/convert/cvt.cc',
    'utf8-ucrt/convert/mbrtoc32.cc',
    'utf8-ucrt/convert/mbrtowc.cc',
    'utf8-ucrt/convert/mbtowc.cc',
    'utf8-ucrt/convert/wctomb.cc',
    'utf8-ucrt/mingw/console.cc',
    'utf8-ucrt/mingw/msvcrt.cc',
    'utf8-ucrt/stdio/fputc.cc',
    'utf8-ucrt/stdio/fputwc.cc',
    'utf8-ucrt/stdio/input.cc',
    'utf8-ucrt/stdio/output.cc',
  }
end

target('utf8-musl.a')
  add_files(table.unpack(utf8_musl_files()))
  add_thunk_flags()
  set_basename('utf8-musl')
  set_kind('static')

target('utf8-musl.so')
  add_files(table.unpack(utf8_musl_files()))
  add_thunk_flags()
  set_basename('utf8-musl')
  set_enabled(has_config('u8crt'))
  set_kind('shared')
