
# wide thunk (-W → -A)
THUNK_LIST_TOOLCHAIN_WIN32W = {
  'kernel32': [
    'CopyFileExW',
    'CopyFileW',
    'CreateDirectoryW',
    'CreateEventW',
    'CreateFileW',
    'CreateProcessW',
    'CreateSemaphoreW',
    'CreateWaitableTimerW',
    'DeleteFileW',
    'FindFirstFileW',
    'FindNextFileW',
    'GetCurrentDirectoryW',
    'GetEnvironmentVariableW',
    'GetFileAttributesExW',
    'GetFileAttributesW',
    'GetFullPathNameW',
    'GetModuleFileNameW',
    'GetTempPathW',
    'MoveFileExW',
    'ReadDirectoryChangesW',
    'RemoveDirectoryW',
    'SetCurrentDirectoryW',
    'SetEnvironmentVariableW',
    'WriteConsoleW',
  ],
}
