from packaging.version import Version

THUNK_LIST_TOOLCHAIN = {
  '3.9999+4.10': {
    'kernel32': [
      'CreateWaitableTimerA',
      'GetFileAttributesExA',
      'SetWaitableTimer',
      'SwitchToThread',
      # followings are i386 atomic thunks
      # Windows 98 (4.10) claim to run on minimum i486, so we place them here
      '__sync_bool_compare_and_swap_4',
      '__sync_fetch_and_add_4',
      '__sync_val_compare_and_swap_4',
    ]
  },
  '4.0': {
    'kernel32': [
      'CancelIo',
      'CopyFileExA',
      'CopyFileExW',
      'CopyFileW',
      'CreateDirectoryW',
      'CreateFileW',
      'CreateProcessW',
      'CreateThread',
      'CreateWaitableTimerW',
      'DeleteFileW',
      'FindFirstFileW',
      'FindNextFileW',
      'GetCurrentDirectoryW',
      'GetEnvironmentVariableW',
      'GetFileAttributesW',
      'GetFileAttributesExW',
      'GetFullPathNameW',
      'GetHandleInformation',
      'GetModuleFileNameW',
      'GetTempPathW',
      'IsDebuggerPresent',
      'LockFileEx',
      'MoveFileExA',
      'MoveFileExW',
      'RemoveDirectoryW',
      'SetCurrentDirectoryW',
      'SetEnvironmentVariableW',
      'SetProcessAffinityMask',
      'TryEnterCriticalSection',
      'UnlockFileEx',
    ],
    'msvcrt': [
      '_wfopen',
    ],
    'shell32': [
      'CommandLineToArgvW',
    ],
  },
  '5.0': {
    'advapi32': [
      'ConvertStringSecurityDescriptorToSecurityDescriptorW',
    ],
    'kernel32': [
      'CreateHardLinkW',
      'CreateToolhelp32Snapshot',
      'FindFirstVolumeW',
      'FindNextVolumeW',
      'FindVolumeClose',
      'GetCPInfoExA',
      'GetFileSizeEx',
      'GetLongPathNameW',
      'GetVolumePathNameW',
      'GlobalMemoryStatusEx',
      'Module32First',
      'Module32Next',
      'SetFilePointerEx',
    ],
    'msvcrt': [
      '_ctime64',
      '_findfirst64',
      '_findnext64',
      ('_fstat64', lambda v_major: v_major < 13),
      '_futime64',
      '_gmtime64',
      '_localtime64',
      ('_stat64', lambda v_major: v_major < 13),
      ('_time64', lambda v_major: v_major < 13),
      '_utime64',
      '_wfindfirst64',
      '_wfindnext64',
      ('_wstat64', lambda v_major: v_major < 13),
      '_wutime64',
    ],
  },
  '5.1': {
    'kernel32': [
      'AddVectoredExceptionHandler',
      'GetConsoleProcessList',
      'GetModuleHandleExW',
      'GetNumaHighestNodeNumber',
      'GetNumaNodeProcessorMask',
      'GetSystemTimes',
      'GetSystemWow64DirectoryA',
      'GetVolumePathNamesForVolumeNameW',
      'RemoveVectoredExceptionHandler',
    ],
    'ws2_32': [
      'freeaddrinfo',
      'getaddrinfo',
      'getnameinfo',
    ],
  },
  '5.2': {
    'advapi32': [
      'RegDeleteKeyExA',
      'RegDeleteKeyExW',
    ],
    'kernel32': [
      'FlsAlloc',
      'FlsFree',
      'FlsGetValue',
      'FlsSetValue',
      'GetCurrentProcessorNumber',
      'GetLargePageMinimum',
      'NeedCurrentDirectoryForExePathA',
      'NeedCurrentDirectoryForExePathW',
    ],
  },
  '6.0': {
    'bcrypt': [
      'BCryptGenRandom',
    ],
    'kernel32': [
      'CancelIoEx',
      'CompareStringOrdinal',
      'CreateSymbolicLinkA',
      'CreateSymbolicLinkW',
      'CreateWaitableTimerExW',
      'DeleteProcThreadAttributeList',
      'GetFileInformationByHandleEx',
      'GetFinalPathNameByHandleA',
      'GetFinalPathNameByHandleW',
      'GetTickCount64',
      'InitializeProcThreadAttributeList',
      'LCMapStringEx',
      'LocaleNameToLCID',
      'SetFileInformationByHandle',
      'UpdateProcThreadAttribute',
    ],
    'msvcrt': [
      '_wputenv_s',
      'wcscat_s',
      'wcscpy_s',
      'wcsncat_s',
      'wcsncpy_s',
      # added in 13 to implement C95 wcstok
      ('wcstok_s', lambda v_major: v_major < 13),
    ],
  },
  '6.1': {
    'kernel32': [
      'GetActiveProcessorCount',
      'GetActiveProcessorGroupCount',
      'GetMaximumProcessorCount',
      'GetMaximumProcessorGroupCount',
      'SetWaitableTimerEx',
    ],
  },
  '6.2': {
    'api-ms-win-core-path-l1-1-0': [
      'PathAllocCanonicalize',
      'PathAllocCombine',
      'PathCchAddBackslash',
      'PathCchAddBackslashEx',
      'PathCchAddExtension',
      'PathCchAppend',
      'PathCchAppendEx',
      'PathCchCanonicalize',
      'PathCchCanonicalizeEx',
      'PathCchCombine',
      'PathCchCombineEx',
      'PathCchFindExtension',
      'PathCchIsRoot',
      'PathCchRemoveBackslash',
      'PathCchRemoveBackslashEx',
      'PathCchRemoveExtension',
      'PathCchRemoveFileSpec',
      'PathCchRenameExtension',
      'PathCchSkipRoot',
      'PathCchStripPrefix',
      'PathCchStripToRoot',
      'PathIsUNCEx',
    ],
    'kernel32': [
      'AddDllDirectory',
      'CopyFile2',
      'GetSystemTimePreciseAsFileTime',
      'RemoveDllDirectory',
    ],
  },
}
