CC  = gcc
CXX = g++

NOWIDE_CXXFLAGS = -std=c++17 -O2
NOWIDE_LIBS     = -lnowide

U8CRT_CFLAGS   += -std=c23 -O2 -mcrtdll=utf8-ucrt
U8CRT_CXXFLAGS += -std=c++23 -O2 -mcrtdll=utf8-ucrt -stdlib=libutf8-stdc++
U8CRT_LDFLAGS  += -mcrtdll=utf8-ucrt -stdlib=libutf8-stdc++

NOWIDE_SRCS  = $(wildcard console/nowide/*.cc)
NOWIDE_EXES  = $(patsubst console/nowide/%.cc,$(DIR)/%.exe,$(NOWIDE_SRCS))
NOWIDE_NAMES = $(patsubst console/nowide/%.cc,%,$(NOWIDE_SRCS))

U8CRT_C_SRCS   = $(filter-out console/u8crt/util.c,$(wildcard console/u8crt/*.c))
U8CRT_C_EXES   = $(patsubst console/u8crt/%.c,$(DIR)/%.exe,$(U8CRT_C_SRCS))
U8CRT_C_NAMES  = $(patsubst console/u8crt/%.c,%,$(U8CRT_C_SRCS))

U8CRT_CXX_SRCS = $(wildcard console/u8crt/*.cc)
U8CRT_CXX_EXES = $(patsubst console/u8crt/%.cc,$(DIR)/%.exe,$(U8CRT_CXX_SRCS))
U8CRT_CXX_NAMES = $(patsubst console/u8crt/%.cc,%,$(U8CRT_CXX_SRCS))

ALL_EXES = $(NOWIDE_EXES)
ALL_NAMES = $(NOWIDE_NAMES)
ifeq ($(U8CRT),y)
ALL_EXES += $(U8CRT_C_EXES) $(U8CRT_CXX_EXES)
ALL_NAMES += $(U8CRT_C_NAMES) $(U8CRT_CXX_NAMES)
endif

all: $(NOWIDE_EXES)
ifeq ($(U8CRT),y)
all: $(U8CRT_C_EXES) $(U8CRT_CXX_EXES)
endif

$(NOWIDE_EXES): $(DIR)/%.exe: console/nowide/%.cc
	$(CXX) $(NOWIDE_CXXFLAGS) $< $(NOWIDE_LIBS) -o $@

$(DIR)/util.o: console/u8crt/util.c
	$(CC) $(U8CRT_CFLAGS) -c $< -o $@

$(U8CRT_C_EXES): $(DIR)/%.exe: console/u8crt/%.c $(DIR)/util.o
	$(CC) $(U8CRT_CFLAGS) $(U8CRT_LDFLAGS) $^ -o $@

$(U8CRT_CXX_EXES): $(DIR)/%.exe: console/u8crt/%.cc $(DIR)/util.o
	$(CXX) $(U8CRT_CXXFLAGS) $(U8CRT_LDFLAGS) $^ -o $@

test-%: $(DIR)/%.exe
	@echo ====== [$*] ======
	@$(subst /,\,$(DIR)/$*.exe)

test: $(foreach name,$(ALL_NAMES),test-$(name))

clean:
	-del $(ALL_EXES)
