name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        profile:
          - 64-ucrt
          - 32-ucrt
          - 64-msvcrt
          - 32-msvcrt
          - 32-win2000
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Fetch container image
        run: |
          podman pull docker.io/amd64/ubuntu:20.04

      - name: Build
        run: |
          podman run --rm -v $PWD:/mnt -w /mnt docker.io/amd64/ubuntu:20.04 ./main.sh --profile ${{ matrix.profile }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: mingw${{ matrix.profile }}
          path: dist/*.7z

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.7z
