name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        branch: [15, 14]
        profile:
          - 64-mcf
          - 64-ucrt
          - 64-msvcrt

          - 32-mcf
          - 32-ucrt
          - 32-msvcrt

          - 32-legacy
        include:
          - prerelease: false
          - prerelease: true
            branch: 15
          - make_latest: false
          - make_latest: true
            branch: 14
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Build
        if: github.ref_type != 'tag' || startsWith(github.ref_name, matrix.branch)
        run: |
          podman pull docker.io/amd64/ubuntu:24.04
          container=$(podman run -dt -v $PWD:/mnt docker.io/amd64/ubuntu:24.04)
          podman exec -w /mnt $container ./support/dep-debian.sh
          podman exec -w /mnt $container ./main.py --branch ${{ matrix.branch }} --profile ${{ matrix.profile }}
          podman kill $container
          podman rm $container

      - name: Upload
        uses: actions/upload-artifact@v4
        if: github.ref_type != 'tag' || startsWith(github.ref_name, matrix.branch)
        with:
          name: mingw${{ matrix.profile }}-${{ matrix.branch }}
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag' && startsWith(github.ref_name, matrix.branch)
        with:
          prerelease: ${{ matrix.prerelease }}
          make_latest: ${{ matrix.make_latest }}
          files: |
            dist/*.7z
            dist/*.tar.zst
