name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        arch: [32, 64]
        crt: [msvcrt, ucrt]
        include:
          - arch: 32
            crt: msvcrt
            nt: '5.1'
          - arch: 64
            crt: msvcrt
            nt: '5.2'
          - crt: ucrt
            nt: '6.0'
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Fetch container image
        run: |
          podman pull docker.io/amd64/ubuntu:20.04

      - name: Build
        run: |
          podman run --rm -v $PWD:/mnt -w /mnt docker.io/amd64/ubuntu:20.04 /mnt/main.sh --arch ${{ matrix.arch }} --compat-level ${{ matrix.nt }} --crt ${{ matrix.crt }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: nt${{ matrix.nt }}-${{ matrix.arch }}-${{ matrix.crt }}
          path: dist/*.7z

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.7z
