name: Build per profile

on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
      release_skip_profile:
        required: true
        type: boolean

jobs:
  build:
    name: Build (${{ matrix.branch }}, ${{ inputs.profile }})
    strategy:
      fail-fast: false
      matrix:
        branch: [16, 15, 14, 13]
        include:
          - prerelease: false
          - { branch: 16, prerelease: true }
          - { branch: 15, prerelease: true }
          - make_latest: false
          - { branch: 14, make_latest: true }
    uses: ./.github/workflows/build_per_profile_per_branch.yml
    with:
      profile: ${{ inputs.profile }}
      branch: ${{ matrix.branch }}
      prerelease: ${{ matrix.prerelease }}
      make_latest: ${{ matrix.make_latest }}
      release_skip_profile_branch: ${{ github.ref_type == 'tag' && (inputs.release_skip_profile || !startsWith(github.ref_name, matrix.branch)) }}

  target_sat_archive:
    name: Target semi-automated testing archive (${{ inputs.profile }})
    if: github.ref_type != 'tag'
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: ConorMacBride/install-package@v1
        with:
          apt: libarchive-tools

      - uses: actions/download-artifact@v4
        with:
          pattern: mingw${{ inputs.profile }}-*
          path: dist
          merge-multiple: true

      - name: Create test archive
        run: |
          ./sat.py -b 16 -p ${{ inputs.profile }}
          ./sat.py -b 15 -p ${{ inputs.profile }}
          ./sat.py -b 14 -p ${{ inputs.profile }}
          ./sat.py -b 13 -p ${{ inputs.profile }}

          (
            cd pkg
            7z a -t7z -mx9 -ms=on -m0=LZMA:d=256m:fb64 ../dist/sat${{ inputs.profile }}.7z sat${{ inputs.profile }}
          )

      - uses: actions/upload-artifact@v4
        with:
          name: sat${{ inputs.profile }}
          path: dist/sat${{ inputs.profile }}.7z
