name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build (${{ matrix.profile }})
    strategy:
      fail-fast: false
      matrix:
        profile: [
          64-mcf, 64-win32, 64-ucrt, 64-msvcrt,
          32-mcf, 32-win32, 32-ucrt, 32-msvcrt,
        ]
    uses: ./.github/workflows/build_per_profile.yml
    with:
      profile: ${{ matrix.profile }}
